import matplotlib.pyplot as plt
import numpy as np

# xin_concentration_mean = np.loadtxt('ave_con_DM_damage_long117.txt')
# xin_concentration_max = np.loadtxt('max_con_DM_damage_long117.txt')
# xin_concentration_min = np.loadtxt('min_con_DM_damage_long117.txt')
# xin_VM_mean = np.loadtxt('ave_VM_DM_damage_long117.txt')
# xin_VM_min = np.loadtxt('min_VM_DM_damage_long117.txt')
# xin_VM_max = np.loadtxt('max_VM_DM_damage_long117.txt')
# xin_D_mean = np.loadtxt('ave_damage_G_DM_damage_long117.txt')
# xin_D_min = np.loadtxt('min_damage_G_DM_damage_long117.txt')
# xin_D_max = np.loadtxt('max_damage_G_DM_damage_long117.txt')
# xin_phi_mean = np.loadtxt('ave_phi_damage_long117.txt')
# xin_phi_min = np.loadtxt('min_phi_damage_long117.txt')
# xin_phi_max = np.loadtxt('max_phi_damage_long117.txt')

# Kristen_concentration_results = np.loadtxt('C_minmeanmax_withdamage_117.txt', delimiter=',')
# Kristen_VM_results = np.loadtxt('sig_VM_minmeanmax_withdamage_117.txt', delimiter=',')
# Kristen_D_results = np.loadtxt('damage_minmeanmax_withdamage_117.txt', delimiter=',')
# Kristen_phi_results = np.loadtxt('Phi_minmeanmax_withdamage_117.txt', delimiter=',')

# Kristen_concentration_results_noIM = np.loadtxt('C_minmeanmax_noIM.txt', delimiter=',')
# Kristen_VM_results_noIM = np.loadtxt('sig_VM_minmeanmax_noIM.txt', delimiter=',')
# Kristen_D_results_noIM = np.loadtxt('damage_minmeanmax_noIM.txt', delimiter=',')
# Kristen_phi_results_noIM = np.loadtxt('Phi_minmeanmax_noIM.txt', delimiter=',')

xin_concentration_mean = np.loadtxt("ave_con_DM_damage_long127_discrete.txt")
xin_concentration_max = np.loadtxt("max_con_DM_damage_long127_discrete.txt")
xin_concentration_min = np.loadtxt("min_con_DM_damage_long127_discrete.txt")
xin_VM_mean = np.loadtxt("ave_VM_DM_damage_long127_discrete.txt")
xin_VM_min = np.loadtxt("min_VM_DM_damage_long127_direct_distance.txt")
xin_VM_max = np.loadtxt("max_VM_DM_damage_long127_direct_distance.txt")
xin_D_mean = np.loadtxt("ave_damage_G_DM_damage_long127_direct_distance.txt")
xin_D_min = np.loadtxt("min_damage_G_DM_damage_long127_direct_distance.txt")
xin_D_max = np.loadtxt("max_damage_G_DM_damage_long127_direct_distance.txt")
xin_phi_mean = np.loadtxt("ave_phi_damage_long127_direct_distance.txt")
xin_phi_min = np.loadtxt("min_phi_damage_long127_direct_distance.txt")
xin_phi_max = np.loadtxt("max_phi_damage_long127_direct_distance.txt")

Kristen_concentration_results = np.loadtxt(
    "C_minmeanmax_withdamage_117.txt", delimiter=","
)
Kristen_VM_results = np.loadtxt("sig_VM_minmeanmax_withdamage_117.txt", delimiter=",")
Kristen_D_results = np.loadtxt("damage_minmeanmax_withdamage_117.txt", delimiter=",")
Kristen_phi_results = np.loadtxt("Phi_minmeanmax_withdamage_117.txt", delimiter=",")


fig1 = plt.figure()
plt.plot(xin_concentration_mean[:], "r", label="Xin")
plt.plot(Kristen_concentration_results[:, 1], "b", label="Kristen")
# plt.plot(Kristen_concentration_results_noIM[:,1], 'g', label = 'Kristen_noIM')
plt.xlabel("time step")
plt.ylabel("mean concentration")
plt.grid()
plt.legend()
# plt.show()

fig2 = plt.figure()
plt.plot(xin_concentration_max[:], "r", label="Xin")
plt.plot(Kristen_concentration_results[:, 2], "b", label="Kristen")
# plt.plot(Kristen_concentration_results_noIM[:,2], 'g', label = 'Kristen_noIM')
plt.xlabel("time step")
plt.ylabel("max concentration")
plt.grid()
plt.legend()
# plt.show()

fig3 = plt.figure()
plt.plot(xin_concentration_min[:], "r", label="Xin")
plt.plot(Kristen_concentration_results[:, 0], "b", label="Kristen")
# plt.plot(Kristen_concentration_results_noIM[:,0], 'g', label = 'Kristen_noIM')
plt.xlabel("time step")
plt.ylabel("min concentration")
plt.grid()
plt.legend()
# plt.show()

fig4 = plt.figure()
plt.plot(xin_VM_mean[:], "r", label="Xin")
plt.plot(Kristen_VM_results[:, 1], "b", label="Kristen")
# plt.plot(Kristen_VM_results_noIM[:,1], 'g', label = 'Kristen_noIM')
plt.xlabel("time step")
plt.ylabel("mean VM")
plt.grid()
plt.legend()
# plt.show()

fig5 = plt.figure()
plt.plot(xin_VM_max[:], "r", label="Xin")
plt.plot(Kristen_VM_results[:, 2], "b", label="Kristen")
# plt.plot(Kristen_VM_results_noIM[:,2], 'g', label = 'Kristen_noIM')
plt.xlabel("time step")
plt.ylabel("max VM")
plt.grid()
plt.legend()
# plt.show()

fig6 = plt.figure()
plt.plot(xin_VM_min[:], "r", label="Xin")
plt.plot(Kristen_VM_results[:, 0], "b", label="Kristen")
# plt.plot(Kristen_VM_results_noIM[:,0], 'g', label = 'Kristen_noIM')
plt.xlabel("time step")
plt.ylabel("min VM")
plt.grid()
plt.legend()
# plt.show()


fig7 = plt.figure()
plt.plot(xin_D_mean[:], "r", label="Xin")
plt.plot(Kristen_D_results[:, 1], "b", label="Kristen")
# plt.plot(Kristen_D_results_noIM[:,1], 'g', label = 'Kristen_noIM')

plt.xlabel("time step")
plt.ylabel("mean damage factor")
plt.grid()
plt.legend()
# plt.show()

fig8 = plt.figure()
plt.plot(xin_D_max[:], "r", label="Xin")
plt.plot(Kristen_D_results[:, 2], "b", label="Kristen")
# plt.plot(Kristen_D_results_noIM[:,2], 'g', label = 'Kristen_noIM')
plt.xlabel("time step")
plt.ylabel("max damage factor")
plt.grid()
plt.legend()
# plt.show()

fig9 = plt.figure()
plt.plot(xin_D_min[:], "r", label="Xin")
plt.plot(Kristen_D_results[:, 0], "b", label="Kristen")
# plt.plot(Kristen_D_results_noIM[:,0], 'g', label = 'Kristen_noIM')
plt.xlabel("time step")
plt.ylabel("min damage factor")
plt.grid()
plt.legend()
plt.show()

# fig10 = plt.plot()
# plt.plot(xin_phi_mean[:], 'r', label = 'Xin')
# plt.plot(Kristen_phi_results[:,1], 'b', label = 'Kristen')
# plt.xlabel('time step')
# plt.ylabel('mean phi')
# plt.grid()
# plt.legend()
# plt.show()

# fig11 = plt.plot()
# plt.plot(xin_phi_max[:], 'r', label = 'Xin')
# plt.plot(Kristen_phi_results[:,2], 'b', label = 'Kristen')
# plt.xlabel('time step')
# plt.ylabel('max phi')
# plt.grid()
# plt.legend()
# plt.show()

# fig12 = plt.plot()
# plt.plot(xin_phi_min[:], 'r', label = 'Xin')
# plt.plot(Kristen_phi_results[:,0], 'b', label = 'Kristen')
# plt.xlabel('time step')
# plt.ylabel('min phi')
# plt.grid()
# plt.legend()
# plt.show()
